name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Step 1 - checkout main branch  from Github
      uses: actions/checkout@v3

    - name: Step 2 - ls
      run: |
        ls
        pwd

    - name: Step 2 - Run Static Tests
      run: python3 -m unittest tests.static.py

    - name: Step 3 - Run Unit Tests
      run: python3 -m unittest tests.unit.py
        
    - name: Step 4 - Build Docker Image
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/pywebappgithub:v$GITHUB_RUN_ATTEMPT  .
        docker run -d --name testing-webapp -p 80:3000 ${{secrets.DOCKERHUB_USERNAME}}/pywebappgithub:v$GITHUB_RUN_ATTEMPT

    - name: Step 5 - Run Smoke Tests
      run: |
        sleep 3
        docker exec testing-webapp python3 -m unittest tests/smoke.py

    - name: Step 6 - Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Step 7 - Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: '${{secrets.DOCKERHUB_USERNAME}}'
        password: '${{secrets.DOCKERHUB_TOKEN}}'

    - name: Step 8 - Build and push to docker hub
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/pywebappgithub:v$GITHUB_RUN_ATTEMPT