name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Step 1 - checkout main branch from Github
      uses: actions/checkout@v3

    - name: Step 2 - Build project
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/pywebappgithub:v1.0.0  .
        docker run -d --name testing-webapp -p 80:3000 ${{secrets.DOCKERHUB_USERNAME}}/pywebappgithub:v1.0.0

    - name: Step 3 - test project
      run: |
        sleep 3
        python3 --version
        python3 -m unittest

    - name: Step 4 - Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Step 4 - Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: '${{secrets.DOCKERHUB_USERNAME}}'
        password: '${{secrets.DOCKERHUB_TOKEN}}'

    - name: Step 5 - Build and push to docker hub
      env:
          version: $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file ./my-app/pom.xml)
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/java-hello:v${{ env.version }}
